import { HardwareDesign, ReviewResult } from './api';

export const mockDesign: HardwareDesign = {
  name: 'Power Control Board',
  purpose: 'Convert 12V input to regulated power and control a 5V relay using a microcontroller.',
  components: [
    { reference: 'F1', name: 'Fuse', type: 'Protection', value: '1A' },
    { reference: 'D1', name: 'Input Protection Diode', type: 'Diode', value: null },
    { reference: 'U2', name: 'LM7805 Voltage Regulator', type: 'Regulator', value: '5V' },
    { reference: 'C1', name: 'Regulator Input Capacitor', type: 'Capacitor', value: '0.1uF' },
    { reference: 'C2', name: 'Regulator Output Capacitor', type: 'Capacitor', value: '0.1uF' },
    { reference: 'U1', name: 'Microcontroller', type: 'IC', value: null },
    { reference: 'R1', name: 'Base Resistor', type: 'Resistor', value: '1kOhm' },
    { reference: 'Q1', name: 'NPN Relay Driver', type: 'Transistor', value: null },
    { reference: 'K1', name: '5V Relay', type: 'Relay', value: '5V' },
  ],
  netlist: [
    { from: '12V_IN', to: 'F1.1' },
    { from: 'F1.2', to: 'D1.A' },
    { from: 'D1.K', to: 'U2.IN' },
    { from: 'U2.GND', to: 'GND' },
    { from: 'U2.OUT', to: '5V_RAIL' },
    { from: 'C1.1', to: 'U2.IN' },
    { from: 'C1.2', to: 'GND' },
    { from: 'C2.1', to: '5V_RAIL' },
    { from: 'C2.2', to: 'GND' },
    { from: '5V_RAIL', to: 'U1.VCC' },
    { from: 'U1.GND', to: 'GND' },
    { from: 'U1.GPIO1', to: 'R1.1' },
    { from: 'R1.2', to: 'Q1.BASE' },
    { from: 'Q1.EMITTER', to: 'GND' },
    { from: 'Q1.COLLECTOR', to: 'K1.COIL' },
    { from: 'K1.COIL', to: '5V_RAIL' },
  ],
  datasheets: [
    {
      component: 'U2',
      constraints: [
        { type: 'InputVoltage', min: 7, max: 25, required: null, approvedValue: null },
        { type: 'OutputVoltage', min: 5, max: 5, required: null, approvedValue: null },
        { type: 'InputCapacitor', min: null, max: null, required: 'Input capacitor', approvedValue: null },
        { type: 'OutputCapacitor', min: null, max: null, required: 'Output capacitor', approvedValue: null },
      ],
    },
    {
      component: 'U1',
      constraints: [
        { type: 'OperatingVoltage', min: 3, max: 3.6, required: null, approvedValue: null },
        { type: 'Decoupling', min: null, max: null, required: '100nF between VCC and GND', approvedValue: null },
      ],
    },
    {
      component: 'K1',
      constraints: [
        { type: 'CoilVoltage', min: 5, max: 5, required: null, approvedValue: null },
        { type: 'FlybackProtection', min: null, max: null, required: 'Flyback diode recommended across relay coil', approvedValue: null },
      ],
    },
    {
      component: 'R1',
      constraints: [
        { type: 'ApprovedDesignValue', min: null, max: null, required: null, approvedValue: '10kOhm' },
      ],
    },
  ],
  engineeringRules: [
    { code: 'PWR001', description: 'Power pins must connect to compatible voltage rails.' },
    { code: 'DEC001', description: 'IC power pins should have appropriate decoupling capacitors.' },
    { code: 'VAL001', description: 'Component values must match approved design values.' },
    { code: 'POL001', description: 'Polarity-sensitive components must be correctly connected.' },
    { code: 'REL001', description: 'Relay drivers should have appropriate flyback protection.' },
    { code: 'GND001', description: 'Required ground connections must exist.' },
    { code: 'PIN001', description: 'Pins must connect according to approved design.' },
  ],
};

export const mockReviewResult: ReviewResult = {
  overallStatus: 'DESIGN_ISSUES_DETECTED',
  score: 72,
  summary: 'Several hardware design issues require review.',
  metrics: {
    components: 9,
    nets: 16,
    datasheets: 4,
    findings: 4,
    critical: 1,
    high: 2,
    medium: 1,
  },
  findings: [
    {
      component: 'U1',
      title: 'Voltage Domain Violation',
      issue: 'U1 supply voltage exceeds the datasheet operating voltage range.',
      severity: 'CRITICAL',
      expected: '3.0V - 3.6V',
      detected: '5V',
      evidence: 'U1.VCC -> 5V_RAIL',
      rule: 'PWR001',
      reason: 'The U1 supply connection exceeds the supplied operating voltage constraint.',
      recommendation: 'Review the U1 power supply rail or component selection.',
      traceability: [
        { stage: 'Circuit', detail: 'U1.VCC' },
        { stage: 'Netlist', detail: '5V_RAIL' },
        { stage: 'Datasheet Agent', detail: 'Max Voltage = 3.6V' },
        { stage: 'Compliance Agent', detail: 'PWR001 violated' },
        { stage: 'Reviewer Agent', detail: 'CRITICAL' },
      ],
    },
    {
      component: 'U1',
      title: 'Missing Decoupling Capacitor',
      issue: 'U1 requires local decoupling between VCC and GND.',
      severity: 'HIGH',
      expected: '100nF between VCC and GND',
      detected: 'Missing',
      evidence: 'U1.VCC -> 5V_RAIL and no capacitor is connected between U1.VCC and GND in the supplied netlist.',
      rule: 'DEC001',
      reason: 'The mock netlist does not show the required U1 decoupling capacitor.',
      recommendation: 'Add or verify a 100nF capacitor between U1.VCC and GND.',
      traceability: [
        { stage: 'Circuit', detail: 'U1.VCC / U1.GND' },
        { stage: 'Datasheet Agent', detail: '100nF between VCC and GND' },
        { stage: 'Netlist', detail: 'No matching capacitor connection' },
        { stage: 'Compliance Agent', detail: 'DEC001 violated' },
        { stage: 'Reviewer Agent', detail: 'HIGH' },
      ],
    },
    {
      component: 'K1',
      title: 'Missing Relay Flyback Protection',
      issue: 'Relay coil does not show flyback protection in the supplied netlist.',
      severity: 'HIGH',
      expected: 'Flyback diode',
      detected: 'Missing',
      evidence: 'K1.COIL connects to Q1.COLLECTOR and 5V_RAIL; no diode is connected across K1.COIL.',
      rule: 'REL001',
      reason: 'Flyback diode is recommended across the relay coil.',
      recommendation: 'Add a flyback diode across the relay coil and verify polarity.',
      traceability: [
        { stage: 'Circuit', detail: 'K1.COIL' },
        { stage: 'Netlist', detail: 'Q1.COLLECTOR -> K1.COIL -> 5V_RAIL' },
        { stage: 'Datasheet Agent', detail: 'Flyback diode recommended' },
        { stage: 'Compliance Agent', detail: 'REL001 violated' },
        { stage: 'Reviewer Agent', detail: 'HIGH' },
      ],
    },
    {
      component: 'R1',
      title: 'Incorrect Component Value',
      issue: 'R1 value does not match the approved design value.',
      severity: 'MEDIUM',
      expected: '10kOhm',
      detected: '1kOhm',
      evidence: 'R1 component value = 1kOhm',
      rule: 'VAL001',
      reason: 'The component value differs from the supplied approved design value.',
      recommendation: 'Update R1 to the approved value or revise the approved design constraint.',
      traceability: [
        { stage: 'Circuit', detail: 'R1' },
        { stage: 'Component Value', detail: '1kOhm' },
        { stage: 'Datasheet Agent', detail: 'Approved Value = 10kOhm' },
        { stage: 'Compliance Agent', detail: 'VAL001 violated' },
        { stage: 'Reviewer Agent', detail: 'MEDIUM' },
      ],
    },
  ],
};
